settings:
  api:
    api_ip: '127.0.0.1'
    api_port: 8111
    indicators_endpoint: '/indicators'
    map_endpoint: '/map_info.json'
    air_info_endpoint: '/state'
  presence:
    show_indicators: True
    lang: en
    logo_theme: main_white
    custom_images: True
  air_indicators:
    air_speed_type: IAS
    altitude_type: RADIO
  logger:
    level: 'TRACE'
  core:
    timeout: 5
    show_notification: True
